### ISSUE TITLE
Layout and UI

### ISSUE THREAD

**Issue by GaurabSubedi7** [GaurabSubedi7/travel_companion#15]
Layout Design
- [x] Profile Layout
- [x] user Post layout
- [x] Responsiveness
- [x] individual post layout
- [x] Dashboard for user
- [x] individual service layout
- [x] Services post layout
- [x] Dashboard for service

**Comment by SuyogAdhikari** [comment]
whaddafak is dynamic profile???

**Comment by SafalKoirala** [comment]
> 
> 
> whaddafak is dynamic profile???
profile pic haru  change garan milne sth like that .

**Comment by SuyogAdhikari** [comment]
- Show user's post 
- Dynamic Profile
These categories do not fall in layout issues... for anyone who creates a feature branch please add these points in features issues.

**Comment by SafalKoirala** [comment]
Clutched in the last moment
