### ISSUE TITLE
Create post and upload photos

### ISSUE THREAD

**Issue by SuyogAdhikari** [GaurabSubedi7/travel_companion#27]
Users  should be able to create a post and upload photos from his gallery

- [x] Upload from gallery
- [x] Store to firebase
- [x] Multiple Images
- [x] Device permission
- [x] Display what images are selected by the user
- [x] Bug Fixes

**Comment by SafalKoirala** [comment]
OMG wow

**Comment by GaurabSubedi7** [comment]
done wayyyyyyyyyyyyyyyyyyy ago
