### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by SuyogAdhikari** [GaurabSubedi7/travel_companion#31]
- [x] Add trips
- [x] Trips recycler view
- [x] Pushing trips to firebase
- [x] adding category dialog box
- [x] adding expenses  to firebase
- [x] expenses view
- [x] retrieveing expenses from firebase
- [x] delete expenses from firebase
- [x] graphical representation of spendings
- [x] addition of locations by users

**Comment by GaurabSubedi7** [comment]
finally done
