### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by SuyogAdhikari** [GaurabSubedi7/travel_companion#32]
**Features Addition**
- [x] Google Map API
- [x] Map view
- [x] Searching 
- [x] Current Location
- [x] Location suggestion
- [x] Retrieve desired location Information and add to firebase

**Bugs/Some Detailing**

- [x] Replace return button to forwarding button on the search keyboard
- [x] Remove new line on search

**Comment by GaurabSubedi7** [comment]
finissssss
