### ISSUE TITLE
Fak All maps and use Google Map

### ISSUE THREAD

**Issue by SuyogAdhikari** [GaurabSubedi7/travel_companion#38]
- [x] Add a map View
- [x] get Current device location
- [x] recenter to current location
- [x] search specific location
- [x] get search location information
- [x] Autocomplete search

**Comment by SuyogAdhikari** [comment]
**Documentation**
https://github.com/osmdroid/osmdroid/wiki

**Comment by SafalKoirala** [comment]
no need of area bounded search
